import Link from "next/link";
import { CheckCircle2, Info } from "lucide-react";
import { BOOKING_CONFIG } from "@/lib/config/booking";

export default function PricingPage() {
  return <main className="min-h-screen bg-slate-50 text-slate-900">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6"><Link href="/" className="font-black">BlankLearn Pricing</Link><nav className="flex items-center gap-4 text-sm font-semibold"><Link href="/" className="text-slate-600">Home</Link><Link href="/teachers" className="text-slate-600">Teachers</Link><Link href="/demo-booking" className="rounded-xl bg-indigo-600 px-4 py-2.5 text-white">Book a demo</Link></nav></div></header>
    <section className="mx-auto max-w-5xl px-4 py-14 sm:px-6"><p className="text-xs font-black uppercase tracking-[.18em] text-indigo-600">Clear pricing</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Know the demo price before you book.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">The demo booking flow shows the confirmed amount, any eligible coupon discount, and payment requirement before checkout.</p>
      <article className="mt-8 max-w-xl rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-bold text-indigo-700">Teacher-led demo class</p><p className="mt-2 text-sm text-slate-600">{BOOKING_CONFIG.demoDurationMinutes}-minute session · Group size up to {BOOKING_CONFIG.groupCapacity}</p></div><p className="text-3xl font-black">₹{BOOKING_CONFIG.pricing.demo}</p></div><div className="my-6 space-y-3 border-y border-slate-100 py-5 text-sm text-slate-700"><p className="flex items-center gap-2"><CheckCircle2 size={17} className="text-emerald-600"/>Choose subject, class and an available time</p><p className="flex items-center gap-2"><CheckCircle2 size={17} className="text-emerald-600"/>Final amount confirmed before payment</p><p className="flex items-center gap-2"><CheckCircle2 size={17} className="text-emerald-600"/>Secure checkout when payment is required</p></div><Link href="/demo-booking" className="block rounded-xl bg-indigo-600 px-5 py-3 text-center text-sm font-bold text-white hover:bg-indigo-700">See available demo times</Link></article>
      <div className="mt-6 flex max-w-xl gap-3 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm leading-6 text-blue-900"><Info className="mt-0.5 shrink-0" size={18}/><p>Regular batch subscription pricing and coin redemption are not available in checkout yet. We’ll publish those prices when enrollment payments are supported.</p></div>
    </section>
  </main>;
}
