"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "@/lib/firebase/client";
import { platformRequest } from "@/lib/platform/client";
type Message = {id:string;text:string;sender:string;at:number};
const answers = {"Joining a class":"Students can join at the scheduled IST time after the teacher opens the class. Teachers can open their classroom from the dashboard.","Demo & pricing":"Your demo schedule appears on your dashboard. After the final demo session, eligible learning plans and savings become available.","Payment help":"Send your booking ID and describe the issue below. Never share your password, OTP, card number or payment credentials."};
export function HelpChat({uid}:{uid?:string}) {
  const [messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[answer,setAnswer]=useState(""),[older,setOlder]=useState<number|null>(null);
  const requestId=useRef("");
  const load=useCallback(async()=>{const data=await platformRequest(`/api/help-chat${uid ? `?uid=${encodeURIComponent(uid)}` : ""}`);setMessages((old)=>Array.from(new Map([...old,...data.messages].map((m:Message)=>[m.id,m])).values()).sort((a,b)=>a.at-b.at));setOlder((old)=>old === null ? data.next : old);},[uid]);
  useEffect(()=>{setMessages([]);setDraft("");setError("");setOlder(null);requestId.current="";let active=true;const stop=onAuthStateChanged(auth,(user)=>{setReady(!!user);if(user)void load().catch(e=>active&&setError(e.message));});const timer=setInterval(()=>{if(auth.currentUser)void load().catch(e=>active&&setError(e.message));},5000);return()=>{active=false;stop();clearInterval(timer);};},[load]);
  async function send(event:React.FormEvent){event.preventDefault();if(!draft.trim()||busy)return;setBusy(true);setError("");requestId.current ||= crypto.randomUUID();try{await platformRequest("/api/help-chat",{method:"POST",body:JSON.stringify({text:draft,requestId:requestId.current,...(uid?{uid}:{})})});setDraft("");requestId.current="";await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 space-y-4"><div><h2 className="text-lg font-bold">{uid ? "Support conversation" : "How can we help?"}</h2><p className="text-xs text-slate-500 mt-1">{uid ? "Reply directly to this member." : "Quick answers below. Send a message to reach the support team; replies appear here."}</p></div>{!uid&&<><div className="flex flex-wrap gap-2">{Object.entries(answers).map(([q,a])=><button type="button" key={q} onClick={()=>setAnswer(a)} className="rounded-full border px-3 py-2 text-xs hover:bg-indigo-50">{q}</button>)}</div>{answer&&<p className="rounded-xl bg-slate-50 p-3 text-sm leading-6">{answer}</p>}</>}
    <div className="h-80 overflow-y-auto space-y-3 rounded-xl bg-slate-50 p-3" role="log" aria-label="Support messages">{older&&<button type="button" className="text-xs text-indigo-600" onClick={async()=>{try{const data=await platformRequest(`/api/help-chat?before=${older}${uid?`&uid=${encodeURIComponent(uid)}`:""}`);setMessages((old)=>Array.from(new Map([...data.messages,...old].map((m:Message)=>[m.id,m])).values()).sort((a,b)=>a.at-b.at));setOlder(data.next);}catch(e){setError((e as Error).message);}}}>Load earlier messages</button>}{!messages.length&&<p className="py-12 text-center text-sm text-slate-500">{ready?"No messages yet. Start a conversation below.":"Sign in to contact support."}</p>}{messages.map(m=><div key={m.id} className={`max-w-[90%] rounded-xl border p-3 ${m.sender==="admin"?"bg-indigo-50 border-indigo-100":"bg-white border-slate-200 ml-auto"}`}><p className="text-[10px] font-bold text-slate-500">{m.sender==="admin"?"Support team":"Member"} / {new Date(m.at).toLocaleString()}</p><p className="mt-1 whitespace-pre-wrap break-words text-sm">{m.text}</p></div>)}</div>{error&&<p role="alert" className="text-sm text-red-600">{error}</p>}<form onSubmit={send} className="flex gap-2"><textarea aria-label="Message to support" maxLength={2000} value={draft} onChange={e=>{setDraft(e.target.value);requestId.current="";}} disabled={busy} placeholder="Describe what you need help with..." className="min-w-0 flex-1 rounded-xl border p-3 text-sm"/><button disabled={!ready||busy||!draft.trim()} className="rounded-xl bg-indigo-600 px-4 text-sm font-bold text-white disabled:opacity-50">{busy?"Sending...":"Send"}</button></form></section>;
}
